In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/cases_deaths/total_cases.csv")

In [3]:
df.isnull().sum()

date                   0
World                  1
Afghanistan           52
Africa                42
Albania               66
                    ...
Vietnam               22
Wallis and Futuna    290
Yemen                 98
Zambia                76
Zimbabwe              78
Length: 247, dtype: int64

In [4]:
data=df.copy()
data=data.sort_values('date')
data=data[data['World'].notna()]

In [6]:
def getMonth(mydate):
    month=mydate[5:7]
    match month:
        case '01':
            return "January"
        case '02':
            return "February"
        case '03':
            return "March"
        case '04':
            return "April"
        case '05':
            return "May"
        case '06':
            return 'June'
        case '07':
            return 'July'
        case '08':
            return "August"
        case '09':
            return "September"
        case '10':
            return "October"
        case '11':
            return "November"
        case '12':
            return "December"
        case _:
            return "invalid month"

In [7]:
from pandas.api.types import CategoricalDtype
cat_size_order = CategoricalDtype(
    ['January2020', 
     'February2020',
       'March2020', 
       'April2020', 
       'May2020',
       'June2020',
       'July2020',
       'August2020',
       'September2020',
       'October2020',
       'November2020',
       'December2020',
       'January2021',
       'February2021',
       'March2021',
       'April2021',
       'May2021',
       'June2021',
       'July2021',
       'August2021',
       'September2021',
       'October2021',
       'November2021',
       'December2021',
       'January2022',
       'February2022',
       'March2022',
       'April2022',
       'May2022',
       'June2022',
       'July2022',
       'August2022',
       'September2022',
       'October2022',
       'November2022',
       'December2022',
       'January2023',
       'February2023',
       'March2023',
       ], 
    ordered=True
)

In [14]:
data['Months']=data['date'].apply(lambda x: getMonth(x))
data['Year'] = data['date'].apply(lambda x: x[0:4])
data['YearMonth']=data['Months'] + data['Year']
World_cases=data.copy()
World_cases=World_cases[['date','World','YearMonth']]
World_cases=World_cases.groupby('YearMonth').sum()
World_cases['YearMonth']=World_cases.index
World_cases['YearMonth']=World_cases['YearMonth'].astype(cat_size_order)
World_cases['index']=[x for x in range(0,len(World_cases))]
World_cases=World_cases.set_index('index')
World_cases=World_cases.sort_values('YearMonth')
World_cases=World_cases.reset_index(drop=True)

In [13]:
World_cases.to_csv('World_cases_monthly.csv')

In [15]:
World_cases

           World      YearMonth
0   3.761000e+04    January2020
1   1.624205e+06   February2020
2   8.681644e+06      March2020
3   6.040411e+07      April2020
4   1.411833e+08        May2020
5   2.422409e+08       June2020
6   4.257386e+08       July2020
7   6.705122e+08     August2020
8   9.029680e+08  September2020
9   1.245392e+09    October2020
10  1.664272e+09   November2020
11  2.286353e+09   December2020
12  2.900688e+09    January2021
13  3.041010e+09   February2021
14  3.739351e+09      March2021
15  4.166935e+09      April2021
16  5.010011e+09        May2021
17  5.293741e+09       June2021
18  5.873146e+09       July2021
19  6.442347e+09     August2021
20  6.789603e+09  September2021
21  7.453464e+09    October2021
22  7.636554e+09   November2021
23  8.469952e+09   December2021
24  1.020189e+10    January2022
25  1.151853e+10   February2022
26  1.432014e+10      March2022
27  1.503941e+10      April2022
28  1.612957e+10        May2022
29  1.608273e+10       June2022
30  1.736503e+10       July2022
31  1.827155e+10     August2022
32  1.825034e+10  September2022
33  1.928834e+10    October2022
34  1.901698e+10   November2022
35  2.077287e+10   December2022
36  2.317464e+10    January2023
37  2.117787e+10   February2023
38  5.313521e+09      March2023